### PR TITLE
added submodules, added build and exec dependencies

### PR DESCRIPTION
**Pull request by vinnnyr**
- ROS navigation now fails on build if attempting to build without geonav transform (I always forget this)

- added geonav as a submodule

### CODE REVIEW

**Comment by droter** [comment]
Thanks for making these changes.

I have the following build error:
  Could not find a package configuration file provided by
  "behaviortree_cpp_v3" with any of the following names:

    behaviortree_cpp_v3Config.cmake
    behaviortree_cpp_v3-config.cmake

**Comment by vinnnyr** [comment]
I added it as an `exec_depend` but I wonder if it needs to be listed as `build_depend` instead

**Comment by droter** [comment]
MBF shuts down then it won't drive a mission.

failure then mbf shuts down

**Comment by vinnnyr** [comment]
This is now turning into a MBF and BT PR. 

test by by using the docker 
```
cd docker/
docker build . -t rosagriculture/tractor_sim
./start.sh
```
Once inside, 
 ```
roslaunch lawn_tractor_sim lawn_tractor_sim.launch 
```
And give the tractor up to 10 waypoints in RVIZ.

**Comment by vinnnyr** [comment]
@droter ready for another round of comments :)

**Comment by droter** [comment]
Builds and runs in the docker container okay now.  No timeouts or build failures.

What is a good test to run for the BT and multiple waypoints?
For example in this package http://wiki.ros.org/follow_waypoints
you use the 2D Pose Estimate and publish points to the topic /waypoints
When you want to drive you send a message here:
rostopic pub /path_ready std_msgs/Empty -1

**Comment by droter** [comment]
Looks great!  Tested in the docker container.

**Pull request merged**
