### PR TITLE
Revert "Update to use namespaces."

### PR DESCRIPTION
**Pull request by droter**
Reverts ros-agriculture/lawn_tractor#23

### CODE REVIEW

**Comment by droter** [comment]
Merged into develop

**Comment by vinnnyr** [comment]
Why the revert ? am I missing something

**Comment by droter** [comment]
Do we want to merge this with develop instead of master?

**Comment by vinnnyr** [comment]
Oh sorry. You closed this branch,. I thought you merged it. All good here!

**Pull request closed without merging**
